services:
  zettnas-toolkit:
    build: .
    image: zettnas-toolkit:latest
    container_name: zettnas-toolkit
    restart: unless-stopped
    labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8082]/"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/fr0styx/zettnas-toolkit/main/static/img/icon.png"
      net.unraid.docker.shell: "bash"
    ports:
      - "${PORT:-8082}:8082"
    volumes:
      - ./app.py:/app/app.py
      - ./static:/app/static
      - /proc:/host/proc:ro
      - /sys:/host/sys:rw
      - /dev:/host/dev:rw
      - /dev/fb0:/dev/fb0
      - /dev/dri:/dev/dri
      - /etc/localtime:/etc/localtime:ro
      - ${STORAGE_POOL_PATH:-/mnt/user}:/mnt/user:ro
      - ./data:/app/data
    environment:
      - LCD_FPS=${LCD_FPS:-10}
      - PORT=8082
      - NAS_NAME=${NAS_NAME:-NAS}
      - POOL_PATH=/mnt/user
      - OS_NVME=${OS_NVME:-nvme1n1}
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_DEV=/host/dev
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
